name: backend
description: PhotoAid backend application

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  crypto: ^3.0.3
  dart_frog: ^1.0.0
  dart_jsonwebtoken: ^2.17.0
  dotenv: ^4.1.0
  latlong2: ^0.9.0
  pointycastle: ^3.9.1
  postgres: ^3.0.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  web_socket_channel: ^2.3.0
  http_parser: ^4.0.2
  http_server: ^1.0.0
  mime: ^1.0.0
  shelf_multipart: ^1.0.0



dev_dependencies:
  http: ^1.1.0
  test: ^1.24.0
  googleapis_auth: ^1.4.0
  crypto: ^3.0.3
  rsa_pkcs: ^2.0.0
