name: backend
description: PhotoAid backend application
version: 1.0.0

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  crypto: ^3.0.3
  dart_frog: ^1.0.0
  dart_jsonwebtoken: ^2.17.0
  dotenv: ^4.1.0
  latlong2: ^0.9.0
  pointycastle: ^3.9.1
  postgres: ^3.5.6
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  web_socket_channel: ^2.3.0
  http: ^1.2.1

dev_dependencies:
  test: ^1.24.0
